name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get latest tag
      id: latest-tag
      uses: actions-ecosystem/action-get-latest-tag@v1

    - name: Build for Linux
      run: |
        env GOOS=linux GOARCH=amd64 go build -o CloudSonic-linux

    - name: Build for Windows
      run: |
        env GOOS=windows GOARCH=amd64 go build -o CloudSonic-windows.exe

    - name: Build for macOS
      run: |
        env GOOS=darwin GOARCH=amd64 go build -o CloudSonic-macos

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.latest-tag.outputs.tag }}
        release_name: Release ${{ steps.latest-tag.outputs.tag }}
        body: Release ${{ steps.latest-tag.outputs.tag }}
      if: startsWith(github.ref, 'refs/tags/')
    
    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CloudSonic-linux
        asset_name: CloudSonic-linux
        asset_content_type: application/octet-stream
    
    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CloudSonic-windows.exe
        asset_name: CloudSonic-windows.exe
        asset_content_type: application/octet-stream
    
    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CloudSonic-macos
        asset_name: CloudSonic-macos
        asset_content_type: application/octet-stream
