name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: |
          VERSION=$(git describe --tags)
          echo "Building version $VERSION"
          go build -o CloudSonic-$VERSION-$GOOS-$GOARCH
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CloudSonic binary
          path: CloudSonic-$VERSION-$GOOS-$GOARCH

  upload-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install ghr
        run: go get -u github.com/tcnksm/ghr
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: CloudSonic binary
      - name: Upload release
        run: |
          echo "Uploading release for version $VERSION"
          ghr --username ${{ github.actor }} --repo CloudSonic --token ${{ secrets.GITHUB_TOKEN }} --replace $VERSION CloudSonic-$VERSION-$GOOS-$GOARCH
